name: my_app
description: "Shorts App"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # supabase
  supabase_flutter: ^2.0.0

  # dependency injection
  get_it: ^7.6.6
  injectable: ^2.3.2

  # state management
  flutter_bloc: ^8.1.3
  equatable: ^2.0.5

  # logging
  logger: ^1.1.0

  # freezed
  freezed_annotation: ^2.4.1
  json_serializable: ^6.7.1

  # routing
  go_router: ^6.2.0

  # toast
  fluttertoast: ^8.2.6

  # image, video
  image_picker: ^1.0.4
  video_editor: ^3.0.0
  video_player: ^2.7.1
  file_picker: ^5.2.2

  # time format
  intl: ^0.18.1
  timeago: ^3.6.0

  # response wrapper
  fpdart: ^1.1.0

  # etc
  flutter_dotenv: ^5.1.0
  smooth_page_indicator: ^1.1.0
  cupertino_icons: ^1.0.2
  ffmpeg_kit_flutter: ^6.0.2
  bottom_sheet: ^4.0.0
  cached_network_image: ^3.2.3
  font_awesome_flutter: ^10.5.0
  fraction: ^5.0.2
  path: ^1.8.3
  path_provider: ^2.1.1
  permission_handler: ^10.4.5
  uuid: ^4.0.0
  flutter_staggered_grid_view: ^0.7.0

dev_dependencies:
  auto_route_generator: ^7.3.1
  build_runner: ^2.4.6
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  injectable_generator: ^2.4.1
  freezed: ^2.4.7

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/icons/
    - assets/images/